version: "3.8"

volumes:
   neo4j_data:
   neo4j_logs:
   neo4j_import:
   neo4j_plugins:

services:
  ui:
    image: ui
    build:
      context: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/app

  api:
    image: api
    depends_on:
      # Make sure the application only starts when the DB is indeed ready
      neo4j:
        condition: service_healthy
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/app

  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_dbms_security_auth__enabled: "true"
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
      # Enable APOC
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*

      # Auto-install APOC
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
       - neo4j_data:/data
       - neo4j_logs:/logs
       - neo4j_import:/import
       - neo4j_plugins:/plugins
    restart: unless-stopped

  # docs:
  #   image: docs
  #   build:
  #     context: ./documentation
  #   ports:
  #   - "9999:9999"
  #   volumes:
  #     - ./documentation:/usr/app

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password123!
  #     PGDATA: /data/postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - /var/lib/postgres:/data/postgres
  #   expose:
  #     - 5432
